#!/bin/sh
# Extracts cjk_fontconfig_match() from src/ui/font_file.h verbatim and compiles
# it against this host's fontconfig, so the Fc code path can be exercised on a
# machine where the #else branch is not otherwise compiled.
#
# The function sits behind `#if defined(_WIN32) / #elif defined(__APPLE__) /
# #else`, so on macOS the real build never compiles it. Copying it by hand
# would test a transcription; extracting the bytes tests the repo.
#
# Usage: tools/fc_match_probe.sh [fontconfig-file]
#   Optional argument: a fonts.conf making an extra directory (e.g. ./Fonts)
#   visible to fontconfig, for testing a font copied off a Linux box.

set -eu
root=$(cd "$(dirname "$0")/.." && pwd)
out=${TMPDIR:-/tmp}/fcmatch_probe
mkdir -p "$out"

# Pull each function out, from its comment block to its closing brace.
extract() {
    awk -v start="^// $1" '
        $0 ~ start { grab = 1 }
        grab { print }
        grab && /^}$/ { exit }
    ' "$root/src/ui/font_file.h"
}

: > "$out/extracted.inc"
for fn in "The file for one family name" "The file for the first face fontconfig offers"; do
    extract "$fn" >> "$out/extracted.inc"
    echo >> "$out/extracted.inc"
done

for want in cjk_fontconfig_match cjk_fontconfig_scan; do
    if ! grep -q "$want" "$out/extracted.inc"; then
        echo "extraction failed: no $want in the output" >&2
        exit 1
    fi
done

{
    echo '// Generated by tools/fc_match_probe.sh -- do not edit.'
    echo '// cjk_fontconfig_match and cjk_fontconfig_scan, extracted verbatim'
    echo '// from src/ui/font_file.h.'
    cat "$out/extracted.inc"
} > "$out/header.inc"

cat > "$out/probe.cpp" <<'EOF'
#include <fontconfig/fontconfig.h>
#include <algorithm>
#include <cstdio>
#include <cstring>
#include <string>
#include <vector>
#include "header.inc"

static const char *kFamilies[] = {
	"Noto Sans CJK", "Noto Sans CJK JP", "Noto Sans CJK SC", "Noto Sans Mono CJK JP",
	"Hiragino Sans", "MS Gothic", "MS PGothic", "Meiryo", "Yu Gothic",
	"DejaVu Sans", "Droid Sans Fallback", "Definitely Not Installed XYZ",
};

int main()
{
	FcInit();
	printf("%-28s %-5s %s\n", "family", "wt", "file returned");
	printf("%-28s %-5s %s\n", "----------------------------", "-----", "--------------------------------");
	int empty = 0, total = 0;
	for (const char *fam : kFamilies)
		for (int b = 0; b < 2; b++, total++) {
			const std::string got = cjk_fontconfig_match(fam, b != 0);
			if (got.empty()) empty++;
			std::string leaf = got;
			const size_t s = leaf.rfind('/');
			if (s != std::string::npos) leaf = leaf.substr(s + 1);
			printf("%-28s %-5s %s\n", fam, b ? "bold" : "reg",
			       leaf.empty() ? "(none)" : leaf.c_str());
		}
	printf("\n%d of %d lookups returned nothing\n", empty, total);

	// The reason this function exists at all: a family that is not installed
	// must come back empty, never as some other font standing in for it. That
	// is what FcFontList gives and FcFontMatch does not.
	puts("\n=== substitution check (all must be empty) ===");
	for (const char *fam : { "Definitely Not Installed XYZ", "No Such Font 12345" }) {
		const std::string got = cjk_fontconfig_match(fam, false);
		printf("  %-32s -> %s\n", fam, got.empty() ? "empty (correct)" : got.c_str());
		if (!got.empty()) printf("      !! substituted a font nobody asked for\n");
	}

	puts("\n=== coverage scan (fontconfig only, no FreeType) ===");
	struct Case { const char *label; std::initializer_list<const char *> langs; } cases[] = {
		{ "one font: ja + en", { "ja", "en" } },
		{ "merge source: ja", { "ja" } },
	};
	for (auto &c : cases) {
		const std::string got = cjk_fontconfig_scan(c.langs);
		std::string leaf = got;
		const size_t sl = leaf.rfind('/');
		if (sl != std::string::npos) leaf = leaf.substr(sl + 1);
		printf("  %-24s -> %s\n", c.label, leaf.empty() ? "(none)" : leaf.c_str());
	}
	return 0;
}
EOF

cxx=${CXX:-c++}
$cxx -std=c++20 -o "$out/probe" "$out/probe.cpp" \
	$(pkg-config --cflags fontconfig) $(pkg-config --libs fontconfig)
echo "built $out/probe"

# The generated config points at this checkout's Fonts/ directory, so the probe
# works wherever it is run rather than at one machine's path. An argument
# overrides it, for a config that sees a different font set.
if [ $# -ge 1 ]; then
    FONTCONFIG_FILE="$1" "$out/probe"
    exit 0
fi
cat > "$out/fonts.conf" <<EOF
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>
  <dir>$root/Fonts</dir>
  <dir>$root/Fonts/noto</dir>
  <cachedir>$out/cache</cachedir>
</fontconfig>
EOF
FONTCONFIG_FILE="$out/fonts.conf" "$out/probe"
